# Generated by Django 4.2.5 on 2023-10-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESPECIALIDAD',
        ),
    ]
