# Generated by Django 4.2.5 on 2023-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Logica', '0002_delete_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPECIALIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=5000)),
            ],
        ),
    ]
