# Generated by Django 4.2.5 on 2023-10-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESPECIALIDAD',
        ),
    ]
