# Generated by Django 4.2.5 on 2023-10-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Logica', '0004_delete_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nomnbre de la Especialidad')),
                ('descripcion', models.CharField(max_length=5000, verbose_name='Descripcion de la Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nomnbre del Docotor')),
                ('alias', models.CharField(max_length=15, verbose_name='Alias del Docotor')),
                ('descripcion', models.CharField(max_length=5000, verbose_name='Descripcion del Doctor')),
                ('telefono', models.IntegerField(null=True)),
                ('whatsapp', models.IntegerField(null=True)),
                ('correo', models.EmailField(max_length=220)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.especialidades')),
            ],
        ),
    ]
