# Generated by Django 4.2.5 on 2023-10-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nomnbre del Servicio')),
                ('descripcion', models.CharField(max_length=5000, verbose_name='Descripcion del Servicio')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_created=True)),
                ('pregunta', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('respuesta', models.CharField(max_length=500, verbose_name='Respuesta')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacciones', models.IntegerField(auto_created=True, default=0)),
                ('fecha', models.DateField(auto_created=True)),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=5000, verbose_name='Descripcion')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.especialidades')),
            ],
        ),
    ]
