# Generated by Django 4.2.5 on 2023-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0006_servicios_preguntas_consejos'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
