# Generated by Django 4.2.5 on 2023-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0007_especialidades_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navegaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('link', models.URLField(choices=[("{% url 'pagina_inicio' %}", 'Inicio'), ("{% url 'pagina_especialidad' %}", 'Especialidad'), ("{% url 'pagina_doctor' %}", 'Doctor'), ("{% url 'pagina_pregunta' %}", 'Preguntas'), ("{% url 'pagina_consejo' %}", 'Consejos'), ("{% url 'pagina_nosotros' %}", 'Nosotros')])),
                ('img', models.ImageField(upload_to='img_inicio/')),
            ],
        ),
        migrations.AddField(
            model_name='consejos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_consejos/'),
        ),
        migrations.AddField(
            model_name='doctores',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_doctores/'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_servicios/'),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_especialidades/'),
        ),
    ]
