# Generated by Django 4.2.5 on 2023-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0008_navegaciones_consejos_img_doctores_img_servicios_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navegaciones',
            name='link',
            field=models.TextField(choices=[("{% url 'pagina_inicio' %}", 'Inicio'), ("{% url 'pagina_especialidad' %}", 'Especialidad'), ("{% url 'pagina_doctor' %}", 'Doctor'), ("{% url 'pagina_pregunta' %}", 'Preguntas'), ("{% url 'pagina_consejo' %}", 'Consejos'), ("{% url 'pagina_nosotros' %}", 'Nosotros')]),
        ),
    ]
