# Generated by Django 4.2.5 on 2023-10-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0010_alter_navegaciones_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navegaciones',
            name='link',
            field=models.CharField(choices=[('pagina_inicio', 'Inicio'), ('pagina_especialidad', 'Especialidad'), ('pagina_doctor', 'Doctor'), ('pagina_pregunta', 'Preguntas'), ('pagina_consejo', 'Consejos'), ('pagina_nosotros', 'Nosotros')], max_length=200),
        ),
    ]
