# Generated by Django 4.2.5 on 2023-10-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0012_alter_servicios_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Logica.especialidades'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logica.especialidades'),
        ),
    ]
