# Generated by Django 4.2.5 on 2023-11-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0014_remove_consejos_reacciones_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
