# Generated by Django 4.2.5 on 2023-12-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logica', '0015_delete_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
